# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='event',
  syntax='proto3',
  serialized_options=b'\n\016proto.grpc.genB\nEventProtoP\001',
  serialized_pb=b'\n\x0b\x65vent.proto\x12\x05\x65vent\"*\n\tEventType\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\"m\n\x05\x45vent\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tvacancies\x18\x04 \x01(\x05\x12\x1d\n\x15\x61\x64\x64itionalInformation\x18\x05 \x03(\t2@\n\rEventNotifier\x12/\n\tsubscribe\x12\x10.event.EventType\x1a\x0c.event.Event\"\x00\x30\x01\x42\x1e\n\x0eproto.grpc.genB\nEventProtoP\x01\x62\x06proto3'
)




_EVENTTYPE = _descriptor.Descriptor(
  name='EventType',
  full_name='event.EventType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='event.EventType.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='event.EventType.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=64,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='event.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='event.Event.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='event.Event.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='event.Event.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vacancies', full_name='event.Event.vacancies', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additionalInformation', full_name='event.Event.additionalInformation', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['EventType'] = _EVENTTYPE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventType = _reflection.GeneratedProtocolMessageType('EventType', (_message.Message,), {
  'DESCRIPTOR' : _EVENTTYPE,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.EventType)
  })
_sym_db.RegisterMessage(EventType)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'event_pb2'
  # @@protoc_insertion_point(class_scope:event.Event)
  })
_sym_db.RegisterMessage(Event)


DESCRIPTOR._options = None

_EVENTNOTIFIER = _descriptor.ServiceDescriptor(
  name='EventNotifier',
  full_name='event.EventNotifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=177,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='event.EventNotifier.subscribe',
    index=0,
    containing_service=None,
    input_type=_EVENTTYPE,
    output_type=_EVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTNOTIFIER)

DESCRIPTOR.services_by_name['EventNotifier'] = _EVENTNOTIFIER

# @@protoc_insertion_point(module_scope)
